import 'package:flutter/material.dart';

class PocadotColors {
  const PocadotColors();

  static const Color primary500 = Color(0xffa3b0ef);
  static const Color primary400 = Color(0xffb7c2f2);
  static const Color primary300 = Color(0xffc9d2f6);
  static const Color primary200 = Color(0xffdae0f9);
  static const Color primary100 = Color(0xffeaedfb);
  static const Color secondary500 = Color(0xffffd300);
  static const Color secondary400 = Color(0xffffdc33);
  static const Color secondary300 = Color(0xffffe566);
  static const Color secondary200 = Color(0xffffed99);
  static const Color secondary100 = Color(0xfffffbe6);
  static const Color alertsStatusSuccess = Color(0xff17d871);
  static const Color alertsStatusInfo = Color(0xff4479ff);
  static const Color alertsStatusWarning = Color(0xffffdc60);
  static const Color alertsStatusError = Color(0xffff6a60);
  static const Color alertsStatusDisabled = Color(0xffd8d8d8);
  static const Color alertsStatusButtonDisabled = Color(0xff8598f9);
  static const Color greyscale900 = Color(0xff212121);
  static const Color greyscale800 = Color(0xff424242);
  static const Color greyscale700 = Color(0xff616161);
  static const Color greyscale600 = Color(0xff757575);
  static const Color greyscale500 = Color(0xff9e9e9e);
  static const Color greyscale400 = Color(0xffbdbdbd);
  static const Color greyscale300 = Color(0xffe0e0e0);
  static const Color greyscale200 = Color(0xffeeeeee);
  static const Color greyscale100 = Color(0xfff5f5f5);
  static const Color greyscale50 = Color(0xfffafafa);
  static const Color othersWhite = Color(0xffffffff);
  static const Color othersBlack = Color(0xff000000);
  static const Color othersRed = Color(0xfff54336);
  static const Color othersPink = Color(0xffea1e61);
  static const Color othersPurple = Color(0xff9d28ac);
  static const Color othersDeepPurple = Color(0xff673ab3);
  static const Color othersIndigo = Color(0xff3f51b2);
  static const Color othersBlue = Color(0xff1a96f0);
  static const Color othersLightBlue = Color(0xff00a9f1);
  static const Color othersCyan = Color(0xff00bcd3);
  static const Color othersTeal = Color(0xff009689);
  static const Color othersGreen = Color(0xff4aaf57);
  static const Color othersLightGreen = Color(0xff8bc255);
  static const Color othersLime = Color(0xffcddc4c);
  static const Color othersYellow = Color(0xffffeb4f);
  static const Color othersAmber = Color(0xffffc02d);
  static const Color othersOrange = Color(0xffff981f);
  static const Color othersDeepOrange = Color(0xffff5726);
  static const Color othersBrown = Color(0xff7a5548);
  static const Color othersBlueGrey = Color(0xff607d8a);
  static const Color darkDark1 = Color(0xff181a20);
  static const Color darkDark2 = Color(0xff1f222a);
  static const Color darkDark3 = Color(0xff35383f);
  static const Color backgroundBlue = Color(0xfff5f7ff);
  static const Color backgroundYellow = Color(0xfffffee0);
  static const Color backgroundOrange = Color(0xfffff8ed);
  static const Color backgroundGreen = Color(0xfff2fffc);
  static const Color backgroundPink = Color(0xfffff5f5);
  static const Color backgroundPurple = Color(0xfffcf4ff);
  static const Color transparentBlue = Color(0x14a3b0ef);
  static const Color transparentYellow = Color(0x14facc15);
  static const Color transparentOrange = Color(0x14ff9800);
  static const Color transparentPurple = Color(0x149c27b0);
  static const Color transparentRed = Color(0x14f75555);
  static const Color transparentGreen = Color(0x144caf50);
  static const Color transparentCyan = Color(0x1400bcd4);
}
