/// Flutter icons PocadotIcons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  PocadotIcons
///      fonts:
///       - asset: fonts/PocadotIcons.ttf
///
///
///
import 'package:flutter/widgets.dart';

class PocadotIcons {
  PocadotIcons._();

  static const _kFontFam = 'PocadotIcons';
  static const String? _kFontPkg = null;

  static const IconData cards = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cardsFilled = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
